name: Check notebooks with papermill

on: [pull_request, push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0} # Required for activation

    steps:
      - uses: actions/checkout@v4
      - name: Setup Micromamba & Cache
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=3.14
          cache-environment: true
          cache-downloads: true

      - name: Check notebooks with papermill
        run: |
          pip install papermill
          papermill "docs/The Delta Method Explained.ipynb"
